server:
  port: 8080

spring:
  application:
    name: contact-service

  datasource:
    url: jdbc:postgresql://postgres:5432/ketemu
    username: ketemu
    password: ketemu

  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:19092

logging:
  level:
    "[io.ketemu.contact]": DEBUG
